name: Checks for every commit

on:
  pull_request: ~
  push:
    branches:
      - master


jobs:
  commitsar:
    name: Verify commit messages
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v1
      - name: Run commitsar
        uses: docker://commitsar/commitsar
